import { Brand } from "@/types/brand";

const brandsData: Brand[] = [
  {
    id: 6,
    name: "Logadex",
    href: "https://www.logadexsrl.com/",
    image: "/images/brands/logadex.png",
    imageLight: "/images/brands/logadex.png",
  },
  {
    id: 1,
    name: "Adafalabella",
    href: "https://www.adafalabella.com.bo/",
    image: "/images/brands/adafalabella.png",
    imageLight: "/images/brands/adafalabella.png",
  },
  {
    id: 2,
    name: "UTB",
    href: "https://utb.edu.bo/",
    image: "/images/brands/utb.png",
    imageLight: "/images/brands/utb.png",
  },
  {
    id: 3,
    name: "Ballivian Group",
    href: "https://www.facebook.com/balliviangroup/?locale=es_LA",
    image: "/images/brands/ballivian.png",
    imageLight: "/images/brands/ballivian.png",
  },
  {
    id: 4,
    name: "TradeCruz",
    href: "https://www.facebook.com/TradecruzSRL/?locale=es_LA",
    image: "/images/brands/tradecruz.jpg",
    imageLight: "/images/brands/tradecruz.jpg",
  },
  {
    id: 5,
    name: "Jetstart",
    href: "https://www.facebook.com/JetStarCargo?locale=es_LA",
    image: "/images/brands/jetstart.png",
    imageLight: "/images/brands/jetstart.png",
  },
  {
    id: 7,
    name: "Agencia Vilaseca",
    href: "https://agencia-vilaseca.com/",
    image: "/images/brands/vilaseca.png",
    imageLight: "/images/brands/vilaseca.png",
  },
  {
    id: 8,
    name: "Maex SRL",
    href: "https://maexboliviaslr.com/",
    image: "/images/brands/maex.png",
    imageLight: "/images/brands/maex.png",
  },
  {
    id: 9,
    name: "Agencia Villatron",
    href: "https://www.boliviaentusmanos.com/amarillas/businesscard/villatron-s-r-l.html",
    image: "/images/brands/villatron.png",
    imageLight: "/images/brands/villatron.png",
  },
  {
    id: 10,
    name: "AGDA",
    href: "https://www.facebook.com/AgenciaAduaneraAGDA/?locale=es_LA",
    image: "/images/brands/agda.png",
    imageLight: "/images/brands/agda.png",
  },
  {
    id: 11,
    name: "Universidad Real",
    href: "https://www.ureal.edu.bo/",
    image: "/images/brands/ureal.png",
    imageLight: "/images/brands/ureal.png",
  },
  {
    id: 12,
    name: "Camex",
    href: "https://camexbolivia.com.bo/",
    image: "/images/brands/camex.png",
    imageLight: "/images/brands/camex.png",
  },
  {
    id: 13,
    name: "Gaciel Bol.",
    href: "https://www.facebook.com/gracielbol/?locale=es_LA",
    image: "/images/brands/gaciel.png",
    imageLight: "/images/brands/gaciel.png",
  },
  {
    id: 14,
    name: "Joyeria Monolito",
    href: "https://www.facebook.com/monolitohechoenbolivia/?locale=es_LA",
    image: "/images/brands/joyeria.png",
    imageLight: "/images/brands/joyeria.png",
  },
  {
    id: 15,
    name: "Gamarra Andes SRL",
    href: "https://gamarraandes.com/",
    image: "/images/brands/gamarra.png",
    imageLight: "/images/brands/gamarra.png",
  },
  {
    id: 16,
    name: "Bruseco SRL",
    href: "https://abruseco.com/",
    image: "/images/brands/bruseco.png",
    imageLight: "/images/brands/bruseco.png",
  },
];

export default brandsData;
